- greeting:
    text_size: xl
    text: Hello, walker

- resources:
    label: System
    cpu: true
    cputemp: true
    memory: true

- resources:
    label: System storage
    disk: /

- resources:
    label: Hot storage
    disk: /mnt/data_lv/