services:
  flood:
    hostname: flood
    image: jesec/flood
    user: 0:0
    command: --port 3001 --allowedpath /downloads
    environment:
      HOME: /config
    volumes:
      - /hot/apps/flood/config:/config
      - /cold/torrents:/downloads
    ports:
      - 3001:3001
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - TZ=Aisa/Yekaterinburg # Your current timezone
    volumes:
      - /hot/apps/transmission/config:/config # Change this to your docker config folder
      - /cold/torrents:/download # Change this to your download folder
    ports:
      - 9091:9091 # Web UI port
      - 51413:51413 # Torrent port (TCP)
      - 51413:51413/udp # Torrent port (UDP)
    restart: unless-stopped # This makes sure that the application restarts when it crashes
