services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
      - 9000:9000
    environment:
      - VIRTUAL_HOST=steel.fmn.com/portainer
      - VIRTUAL_PORT=9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  data:
